const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
var firstelement = languages[0];
console.log('The first element of the array is ' + firstelement);
var thirdelement = languages[2];
console.log('The 3rd element of the array is ' + thirdelement);
var length = languages.length;
console.log('The length of the array is ' + length);
var lastelement = length - 1;
console.log('The last element of the array is ' + languages[lastelement]);
